### ISSUE TITLE
Does not show the spades/clubs/diamonds/hearts pictures (V0.8)

### ISSUE THREAD

**Issue by velnias75** [velnias75/NetMauMau-Qt-Client#13]
_From @jimazas on January 11, 2015 20:20_

When a Jack(J) is thrown and you have to pick between the 4 colours with the pop up window, it displays only a black or red bar instead of the pictures of spade,clubs,diamonds and hearts. The same thing happens when the opponent throws a Jack(J) and it should display these pictures below the thrown cards.

_Copied from original issue: velnias75/NetMauMau#18_

**Comment by velnias75** [comment]
It seems that your system font has no Card symbols and/is no Unicode font.
Can you provide more info please:

* Version of NetMauMau
* Operating system (if not Windows, than also the Desktop environment)
* used system font if nown or at least a screen shot

**Comment by jimazas** [comment]
I am using NetMauMau Qt Client 0.8 on Windows 7. Here are some screenshots:
![untitled](https://cloud.githubusercontent.com/assets/9749050/5700283/5e0318c6-9a44-11e4-859b-6a05b8e7b36d.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/9749050/5700284/5e0e54b6-9a44-11e4-94ac-489a66d045b5.jpg)

**Comment by velnias75** [comment]
OMG, how much I hate that **Winf*ck** (sorry). On my virtual machine it works fine and according the screenshots you are not using a too much modified Win theme. But maybe suit symbols are a feature only available only in *Ultimate edition*? 

I've implemented a test if suit symbols are existing in the system font. If not, fallback images are used.
Are you willing to test it, but not to distribute this test version?

**Comment by jimazas** [comment]
I am not using Ultimate Edition. Yes I can give it a try.

**Comment by velnias75** [comment]
@jimazas Please download the [Testversion](http://rangun.de/NetMauMau-0.10.exe) and tell me after you have installed, so I can remove the file.

**Comment by jimazas** [comment]
Same thing as before.
![untitled](https://cloud.githubusercontent.com/assets/9749050/5704577/9774dc48-9a7b-11e4-80d8-b656b80e6d9e.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/9749050/5704578/977e596c-9a7b-11e4-9a1f-119877d0a147.jpg)

**Comment by velnias75** [comment]
So I have no plan for the moment what the error could be. I'm actually tired of all this damn **Winf*ck** exceptions.
On Linux it works like charm, even on Windows 7 in my virtual box. It looks like a font problem on your PC. The code now checks if it can display the suit symbols and apparently your PC gives the wrong answer. Does your PC display this [section](http://en.wikipedia.org/wiki/Suit_%28cards%29#Character_encodings) of Wikipedia correct?

**Comment by jimazas** [comment]
Yes it is displayed correctly.

**Comment by velnias75** [comment]
So I have absolutely no plan what is going wrong :disappointed:

**Comment by velnias75** [comment]
In the messages, are the suits displayed correctly?

**Comment by velnias75** [comment]
@jimazas I will try to make the check on UTF-16, which is used by Windows.
It will take a few moments, but are you willing to test again than?

**Comment by jimazas** [comment]
No, they are displayed the same as the screenshots. Yes, I'll give it a try.

**Comment by velnias75** [comment]
@jimazas the same URL, can you try again?

**Comment by velnias75** [comment]
I could reproduce that bar problem at least somewhere else in the German translation.
I guess I need to dig into that problem a bit deeper...

**Comment by jimazas** [comment]
Same thing again.

**Comment by velnias75** [comment]
Ok, I try to find a solution. Somehow I will get to reproduce that.

If not, I will generally use the fallback code on Windows. The official V0.10 
will in any way show no more that behaviour.

Nobody anymore should tell me **Windows** is in any case superior to Linux. 
There everything works like charm, while I'm **forced** to disable 
functionality on Windows.

This font problem is not he only thing I had to disable, just because it is 
not possible without **massive** effort...

**Comment by velnias75** [comment]
https://github.com/velnias75/NetMauMau-Qt-Client/commit/3f0133d6f1b214d5c8e58b2c64c3ebed992dac78 partially fixes that issue, by just always use the fall-back images and texts. But since I cannot reproduce it on my Windows 7 in the VM, the Win32 community must suffer another drawback and disabled feature.

Why must I rewrite almost **all** trivial code to satisfy this strange operating system? On **Linux** it simply works!

**Comment by velnias75** [comment]
@jimazas After digging into the totally broken Font handling of Win32 (I wonder that Windows can show any text at all) as well as into the Bug tracker of Qt I may have found a solution.
If you are willing to test again, please [download](http://rangun.de/NetMauMau-0.10.exe) it again.

If it is not working, can you offer me a screen shot of the messages as well the suit choice dialog after done a few turns? It should show up the font used (on my installation *MS Shell Dlg*)

As work around you can play around with the Font for *Symbol* in the *Appearance* settings. The font which is chosen for *MS Shell Dlg* you can set in the registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\Current Version\FontSubstitutes` ([See here](http://msdn.microsoft.com/en-us/library/dd374112%28VS.85%29.aspx))

**Comment by jimazas** [comment]
I tested it and it works.

**Comment by velnias75** [comment]
That are the new I *like* :smiley:
