### ISSUE TITLE
NetMauMau cannot recover from crashing

### ISSUE THREAD

**Issue by Taknamay** [velnias75/NetMauMau-Qt-Client#29]
Sometimes NetMauMau crashes, and when I try to restart, I get this message:

"NetMauMau is already running!"

I try to kill all the processes, but it keeps giving me that message! Only when I restart it goes away.

**Comment by velnias75** [comment]
The crashes would be more interesting :grin: 

Currently if the client is running is determined via shared memory which is not freed at a crash.
As temporary solution you need find the *shm-id* with `ipcs` and then remove it with `ipcrm -m <shm-id>`

I'm thinking about a *crash-safe* way to determine if the client is already running.

**Comment by velnias75** [comment]
I replaced the code with a lock file. If that file `/tmp/NetMauMau Qt Client_USER.lck` is locked, than another instance by that *USER* raises the message. At a crash the OS removes that lock, so afterwards the client can get started again as normal.
